services:
  my-jenkins:
    build:
      context: .
    container_name: my-jenkins
    restart: on-failure
    user: root # Belangrijk: om de socket op je Mac te mogen lezen
    privileged: true
    environment:
      # We vertellen Jenkins dat hij NIET naar het netwerk moet kijken, maar naar de lokale socket
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # De directe 'tunnel' naar Docker Desktop
    ports:
      - "8090:8080"
      - "50000:50000"

volumes:
  jenkins-data: